# include Chai3d
find_package(CHAI3D REQUIRED)
include_directories(${CHAI3D_INCLUDE_DIRS})
add_definitions(${CHAI3D_DEFINITIONS})
link_directories(${CHAI3D_LIBRARY_DIRS})

# SAI2-SIMULATION
find_package(SAI2-SIMULATION REQUIRED)
include_directories(${SAI2-SIMULATION_INCLUDE_DIRS})
add_definitions(${SAI2-SIMULATION_DEFINITIONS})

# SAI2-GRAPHICS
find_package(SAI2-GRAPHICS REQUIRED)
include_directories(${SAI2-GRAPHICS_INCLUDE_DIRS})
add_definitions(${SAI2-GRAPHICS_DEFINITIONS})

# SAI2-COMMON
find_package(SAI2-COMMON REQUIRED)
include_directories(${SAI2-COMMON_INCLUDE_DIRS})

# SAI2-URDF
find_package(SAI2-URDF REQUIRED)
include_directories(${SAI2-URDF_INCLUDE_DIRS})

set(SAI2-PRIMITIVES_TESTS_COMMON_LIBRARIES
${SAI2-MODEL_LIBRARIES}
${SAI2-GRAPHICS_LIBRARIES}
${SAI2-SIMULATION_LIBRARIES}
${SAI2-COMMON_LIBRARIES}
${SAI2-URDF_LIBRARIES}
${CHAI3D_LIBRARIES}
)

# TESTS folder
set(TESTS_FOLDER "${CMAKE_CURRENT_SOURCE_DIR}")
add_definitions(-DTESTS_FOLDER="${TESTS_FOLDER}")

add_subdirectory(01-puma)