name: 'Build'
description: 'Builds the repository'
inputs:
  token:
    description: 'token to download artifacts'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      uses: manips-sai-org/sai2-common/custom_github_actions/dependencies@master

    - name: Setup Sai2-urdfreader
      uses: manips-sai-org/sai2-common/custom_github_actions/sai2-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: sai2-urdfreader
        
    - name: Setup Sai2-model
      uses: manips-sai-org/sai2-common/custom_github_actions/sai2-model@master
      with:
        token: ${{ inputs.token }}

    - name: Setup chai3d
      uses: manips-sai-org/sai2-common/custom_github_actions/sai2-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: chai3d

    - name: Setup Sai2-Graphics
      uses: manips-sai-org/sai2-common/custom_github_actions/sai2-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: sai2-graphics

    - name: Setup Sai2-Common
      uses: manips-sai-org/sai2-common/custom_github_actions/sai2-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: sai2-common

    - name: Setup Sai2-Simulation
      uses: manips-sai-org/sai2-common/custom_github_actions/sai2-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: sai2-simulation

    - name: Build Sai2-primitives
      shell: bash
      run: |
        export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:dep/*
        cd ruckig
        mkdir build && cd build
        cmake .. && make -j8
        cd ../..
        mkdir build && cd build
        cmake .. && make -j8

    - name: Check build status
      shell: bash
      run: |
        cd build
        make --always-make --dry-run