# Self-collilsion config
collision_config:
  link_names: ["link0", "link1", "link2", "link3", "link4", "link5", "link6", "link7", "end-effector"]
  mesh_prefix: /home/william/OpenSai/core/sai2-primitives/openGJK/utils/panda_meshes/
  mesh_names: ["link0.dat", "link1.dat", "link2.dat", "link3.dat", "link4.dat", "link5.dat", "link6.dat", "link7.dat", "hand.dat"]
  pairs: 
    # - (0, 2)
    # - (0, 3)
    # - (0, 4)
    # - (0, 5)
    # - (0, 6)
    # - (0, 7)
    - [0, 8]
    # - [1, 3]
    # - (1, 4)
    # - (1, 5)
    # - (1, 6)
    # - (1, 7)
    - [1, 8]
    # - (2, 4)
    # - (2, 5)
    # - (2, 6)
    # - (2, 7)
    - [2, 8]
    # - [3, 5]
    # - (3, 6)
    # - (3, 7)
    - [3, 8]
    # - (4, 6)
    # - (4, 7)
    - [4, 8]
    # - (5, 7)
    # - [5, 8]
    # - [6, 8]